language: python
python:
  - "3.7-dev"
before_install:

  # Here we just install Miniconda, which you shouldn't have to change.

  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  
install:
  - conda env create -q --file monica-requirements.yml
  - source activate monica


script:
  - python -m unittest
