language: python
python:
  - "3.7-dev"
before_install:

  # Here we just install Miniconda, which you shouldn't have to change.

  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda env create -q --file monica-requirements.yml --force
  - source activate monica


script:
  - python -m unittest discovery
